version: '2'
services:
  mqp:
    image: rabbitmq:3.6.6
    ports:
      - "5672:5672"

  db:
    image: postgres:9.6.2
    ports:
      - "5432:5432"

  client:
    build:
      context: ./post-client
    links:
      - mqp
    volumes:
      - .:/myapp

  provider:
    build:
      context: ./post-provider
    command: rails server -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    links:
      - db
      - mqp
    volumes:
      - .:/myapp
